baseURL: 'https://leecalvink.net/'
canonifyUrls: 'true'
disableHugoGeneratorInject: 'true'
disableKinds:
  - taxonomy
  - term
enableRobotsTXT: 'false'
languageCode: 'en-us'
sitemap:
  filename: 'sitemap.xml'
title: 'The Official Site for Lee Calvin Kierstead'
